title: System on a Consciousness
description: Some words, some code.
theme: just-the-docs
baseurl: "/soc"
url: "https://bignacio.github.io"

permalink: pretty

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - .github

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

enable_copy_code_button: true
heading_anchors: true

aux_links:
  "C++ Performance Articles":
    - "https://bignacio.github.io/cpp-articles"

aux_links_new_tab: false

# left panel navigation
# nav_external_links:
#   - title: SoC
#     url: https://bignacio.github.io/soc

back_to_top: true
back_to_top_text: "Back to top"


color_scheme: nil

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false